    <footer>
        <div class="container-3"> 
            <ul class="container-3-ul">
                <li class="footer-li">
                    <div class="li-1-div">
                        <h4 class="company">RR Company</h4>
                        <br>
                        <br>
                        <ul class="footer-col-ul">
                            <li><a class="li" href="https://youtu.be/qAP6ejgkSN0">YouTube Link</a></li>
                            <br>
                            <li><a class="li" href="#">Our Services</a></li>
                            <br>
                            <li><a class="li" href="#">Privacy Policy</a></li>
                        </ul>
                    </div>
                </li>
                <li class="footer-li">
                    <div class="li-2-div">
                        <h4 class="company">Get Help</h4>
                        <br>
                        <br>
                        <ul class="footer-col-ul">
                            <li><a class="li" href="#">FAQ</a></li>
                            <br>
                            <li><a class="li" href="#">Payment Options</a></li>
                            <br>
                            <li><a class="li" href="#">Order Status</a></li>
                        </ul>
                    </div>
                </li>
                <li class="footer-li">
                    <div class="li-3-div">
                        <h4 class="company">Follow Us</h4>
                        <br>
                        <br>
                        <ul class="footer-col-ul">
                            <li><img class="instagram-img" src="image/Instagram.png" alt="instagram"><a class="li" href="#">  Instagram</a></li>
                            <br>
                            <li><img class="facebook-img" src="image/Facebook.png" alt="facebook"><a class="li" href="#">  Facebook</a></li>
                            <br>
                            <li><img class="twitter-img" src="image/Twitter.png" alt="twitter"><a class="li" href="#">  Twitter</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </footer>