    <header>
        <nav>
            <label class="logo">The Reel Room</label>
            <ul> 
                <li><a href="index.php">Home</a></li>
                <li><a class="active" href="product.php">Product</a></li>
                <li><a href="payment.php">Enquiry</a></li>
                <li><a href="about.php">About</a></li>
                <li><a href="enhancement.php">Enhancement</a></li>
                <li><a href="management.php">Management</a></li>
            </ul>
        </nav>
    </header>